name: Verify Pull Request

on:
  workflow_call:
    secrets:
      GH_PACKAGES_USERNAME:
        required: true
      GH_PACKAGES_TOKEN:
        required: true
      GH_WORKFLOW_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - name: Setup Cache
        id: maven-cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ github.repository }}-maven
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          # server-id: avanet-github # Value of the distributionManagement/repository/id field of the pom.xml
          # settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Build with Maven
        run: mvn verify -s local-settings.xml --batch-mode
        env:
          GITHUB_USERNAME: '${{ secrets.GH_PACKAGES_USERNAME }}'
          GITHUB_TOKEN: '${{ secrets.GH_PACKAGES_TOKEN }}'
      - name: Retrieve Suppression File
        run: |
          curl -H "Authorization: token ${GH_WORKFLOW_TOKEN}" https://raw.githubusercontent.com/ava-monitoring/avanet-parent/master/avanet-build-common/src/main/resources/owasp-dependency-check-suppressions.xml > owasp-dependency-check-suppressions.xml
        env:
          GH_WORKFLOW_TOKEN: '${{ secrets.GH_WORKFLOW_TOKEN }}'
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
            --suppression owasp-dependency-check-suppressions.xml
            --exclude **/target/quarkus-app/quarkus-run.jar
            --exclude **/avanet-*.jar
        env:
          JAVA_HOME: /opt/jdk
      - name: Upload Test results
        uses: actions/upload-artifact@master
        if: success() || steps.depcheck.outcome == 'failure'
        with:
          name: Dependency Check Report
          path: ${{github.workspace}}/reports