name: Verify Pull Request

on:
  workflow_call:
    secrets:
      GH_PACKAGES_USERNAME:
        required: true
      GH_PACKAGES_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          # server-id: avanet-github # Value of the distributionManagement/repository/id field of the pom.xml
          # settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Build with Maven
        run: mvn verify -s local-settings.xml --batch-mode
        env:
          GITHUB_USERNAME: '${{ secrets.GH_PACKAGES_USERNAME }}'
          GITHUB_TOKEN: '${{ secrets.GH_PACKAGES_TOKEN }}'