# Workflow that creates a Pull Request where the property that holds the version of a dependency is bumped to a new version.

name: Dependency version property bump

on:
  workflow_call:
    inputs:
      lib-name:
        required: true
        type: string
      version:
        required: true
        type: string
      requester:
        required: true
        type: string
    secrets:
      BOT_APP_ID:
        required: true
      BOT_APP_PRIVATE_KEY:
        required: true
      GH_PACKAGES_USERNAME:
        required: true
      GH_PACKAGES_TOKEN:
        required: true

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Bump dependency version
        run: |
          mvn -s local-settings.xml --batch-mode \
            versions:set-property \
            -Dproperty=${{ inputs.lib-name }}.version \
            -DnewVersion=${{ inputs.version }} \
            -DgenerateBackupPoms=false
        env: # Credentials allowed to fetch packages from other repos
          GITHUB_USERNAME: '${{ secrets.GH_PACKAGES_USERNAME }}'
          GITHUB_TOKEN: '${{ secrets.GH_PACKAGES_TOKEN }}'

      - name: Generate App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      # This won't do anything if there was no change above. We could have used grep to check.
      - uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          base: master
          branch: deps/${{ inputs.lib-name }}-${{ inputs.version }}
          commit-message: "chore: bump ${{ inputs.lib-name }} to ${{ inputs.version }}"
          title: "Bump ${{ inputs.lib-name }} to ${{ inputs.version }}"
          body: |
            Automated version bump for property `${{ inputs.lib-name }}.version` to `${{ inputs.version }}`.
          # author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          # committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          # assignees: ${{ inputs.requester }}
          reviewers: ${{ inputs.requester }}